### ISSUE TITLE
Saying Hi

### ISSUE THREAD

**Issue by bztsrc** [neilpopham/tic80#1]
Hi @neilpopham,

Not sure if you're still maintaining this repo, but I wanted to let you know that I've created a [PICO-8 to TIC-80](https://bztsrc.gitlab.io/p8totic/) online cartridge converter.

If you're still around, I just wanted to know what do you think about it, maybe you have some idea how to improve.

Cheers,
bzt

**Comment by neilpopham** [comment]
Hey, thanks for letting me know. I'll give it a try.

**Comment by bztsrc** [comment]
@neilpopham: Well? Did it work you?

Cheers,
bzt

**Comment by neilpopham** [comment]
@bztsrc It downloads a TIC file and I didn't want to load a TIC file I couldn't trust, so went no further.

I would rather a LUA file option, for those of us with the Pro version, so I can see the code.

**Comment by bztsrc** [comment]
> I didn't want to load a TIC file I couldn't trust

Forgive me, that's a pretty lame excuse. Why can't you trust a data file, with no native binary code, running only inside TIC-80? Also, my tool is FOSS, you can take a look at it's source code, nothing "malicious" is put into the .tic...

> I would rather a LUA file option

The [.tic](https://github.com/nesbox/TIC-80/wiki/.tic-File-Format) format is the TIC-80's standard cartridge format, which includes the Lua code as-is in plain text (in the [code](https://github.com/nesbox/TIC-80/wiki/.tic-File-Format#code) chunk to be precise).

If you don't want to load the .tic file (there's absolutely no reason why you shouldn't, it's only running *inside* an emulator, not on your computer), just open it with any hexviewer and copy'n'paste the Lua code out.

BTW, pure Lua file option is not possible, because this converter converts not just the code, but the assets as well, so using the TIC-80 standard cartridge format is only logical.

Anyway, happy new year!

Cheers,
bzt

**Comment by neilpopham** [comment]
I don't think I need an "excuse" not to use your tool. Please leave me
alone.

Thanks,

**Comment by bztsrc** [comment]
I was just trying to point out, if you don't want to use a tool, then be a man and say so, and lot something shady as "I don't like that it uses the standard TIC-80 format"...

I won't bother you any more.

Cheers,
bzt
